name: components_codelab
description: An AngularDart app that simulates a lottery
version: 0.0.1

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^4.0.0-beta
  angular_components: ^0.6.0-beta
  intl: ^0.14.0

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- angular:
    entry_points: web/main.dart
- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc
