name: captains_log
version: 0.0.1
description: >
  A starship captain's log with a WYSIWYG editor. Uses an existing JavaScript
  library with the new Dart JS-interop.

environment:
  sdk: '>=1.17.0 <2.0.0'

dependencies:
  func: ^0.1.0
  js: ^0.6.1
  browser: ^0.10.0
  html: ^0.13.0
  dart_to_js_script_rewriter: ^1.0.1
