name: server_code_lab
version: 0.1.0
author: Dart Team <misc@dartlang.org>
description: Code-lab server sample.
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  _discoveryapis_commons: ^0.1.0
  browser: ^0.10.0+2
  crypto: ^0.9.0
  http: ^0.11.1
  logging_handlers: ^0.8.0
  rpc: ^0.5.0

homepage: https://www.dartlang.org/codelabs/server/
