name: pirate_badge
version: 0.0.0
description: 
author: Kasper Peulen <kasperpeulen@gmail.com>
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  browser: ^0.10.0+2
  angular2: ^2.0.0-beta.0
  dart_to_js_script_rewriter: ^0.1.0+4
transformers:
- angular2:
    entry_points: web/main.dart
- dart_to_js_script_rewriter
dev_dependencies:
  grinder: ^0.8.0+1
  peanut: ^0.0.1+2
  git: ^0.4.4+2
